### PR TITLE
(#1030) ComparableText is not equal to the same text

### LINKED ISSUE #1030: ComparableText is not equal to the same text
```
Text text = new TextOf("abc");
final Text a = new ComparableText(
    text
);
final Text b = new ComparableText(
    text
);
System.out.format("a.equals(b)==%s", a.equals(b));
```

What's wrong:
a.equals(b)==false

Expected result:
a.equals(b)==true

### PR DESCRIPTION
**Pull request by ilyakharlamov**
This PR:
- #1030 
- Adds unit tests for #1030

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1031](https://github.com/yegor256/cactoos/issues/1031) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1031](https://github.com/yegor256/cactoos/issues/1031) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/8a3b4e7d-78e2-46b4-97e9-2d87b696356a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

File: src/main/java/org/cactoos/text/ComparableText.java [hunk 1]
```diff
@@ -69,4 +70,24 @@ public String asString() throws Exception {
         return this.text.asString();
     }
 
+    @Override
+    public boolean equals(final Object other) {
```
Comment (fabriciofx) [inline src/main/java/org/cactoos/text/ComparableText.java]: @ilyakharlamov Please, use `Equals` instead.

File: src/main/java/org/cactoos/text/ComparableText.java [hunk 2]
```diff
@@ -69,4 +70,24 @@ public String asString() throws Exception {
...
+                this.text,
+                ((ComparableText) other).text
+            );
+        }
+        return result;
+    }
+
+    @Override
+    public int hashCode() {
+        return Objects.hash(this.text);
```
Comment (fabriciofx) [inline src/main/java/org/cactoos/text/ComparableText.java]: @ilyakharlamov Let's avoid use static methods.

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 3]
```diff
@@ -68,4 +71,52 @@ public void comparesToUncheckedText() {
             Matchers.equalTo(0)
         );
     }
+
+    @Test
+    public void equalsAndHashCodeOfComparableOfTheSameText() {
+        final Text text = new TextOf("my text");
+        final Text actual = new ComparableText(text);
+        final Text expected = new ComparableText(text);
+        MatcherAssert.assertThat(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Use `Assertion` instead.

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 4]
```diff
@@ -68,4 +71,52 @@ public void comparesToUncheckedText() {
...
+            "Does not equal to a comparable text made from the same Text",
+            actual,
+            new IsEqual<>(
+                expected
+            )
+        );
+        MatcherAssert.assertThat(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Same above.

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 5]
```diff
@@ -68,4 +71,52 @@ public void comparesToUncheckedText() {
...
+            )
+        );
+    }
+
+    @Test
+    public void equalsOfDifferentText() {
+        final Text text = new ComparableText(
+            new TextOf("my value")
+        );
+        MatcherAssert.assertThat(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Same above.

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 6]
```diff
@@ -68,4 +71,52 @@ public void comparesToUncheckedText() {
...
+            "Is equal to the completely different object",
+            text,
+            new IsNot<>(
+                new IsEqual<>(
+                    new Object()
+                )
+            )
+        );
+        MatcherAssert.assertThat(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Same above.

File: src/main/java/org/cactoos/text/ComparableText.java (hunk 1 above)
Comment (ilyakharlamov) [reply src/main/java/org/cactoos/text/ComparableText.java]: @fabriciofx 
Sorry, I am not familiar with the Equals object, how is it supposed to be used if the object you compare it against is `Object`, not `Scalar`?
I tried searching for some doc and description couldn't find any relevant example of such a case.
is that supposed to be an unsafe cast like ```new Equals(this.field, (Scalar) other)``` or what?

Comment (fabriciofx) [reply src/main/java/org/cactoos/text/ComparableText.java]: @ilyakharlamov If there isn't documentation enough to understand `Equals` usage it can be a bug. Can you open an issue about it? Thanks!

Comment (fabriciofx) [reply src/main/java/org/cactoos/text/ComparableText.java]: @ilyakharlamov You can use something like: `new Equals(() 0-> this.field1, () -> this.field2).value()` or something like that. WDYT?

File: src/test/java/org/cactoos/text/ComparableTextTest.java (hunk 3 above)
Comment (ilyakharlamov) [reply src/test/java/org/cactoos/text/ComparableTextTest.java]: @fabriciofx  Assertion is in cactoos-matchers since 0.13, it's not available yet

Comment (fabriciofx) [reply src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Let's wait for #1023.

File: src/main/java/org/cactoos/text/ComparableText.java (hunk 2 above)
Comment (ilyakharlamov) [reply src/main/java/org/cactoos/text/ComparableText.java]: @fabriciofx wait for #978 I guess

File: src/main/java/org/cactoos/text/ComparableText.java (hunk 1 above)
Comment (ilyakharlamov) [reply src/main/java/org/cactoos/text/ComparableText.java]: Sorry, I tried to find, but don't understand how to use `new Equals` in the `boolean equals(Object other)` method. There are a few problems:
- `new Equals<>(
                    () -> ...Text
                    () -> ...Text
                )` obviousy does not compile.

File: src/main/java/org/cactoos/text/ComparableText.java (hunk 2 above)
Comment (ilyakharlamov) [reply src/main/java/org/cactoos/text/ComparableText.java]: @fabriciofx fixed in 93445f16

File: src/main/java/org/cactoos/text/ComparableText.java (hunk 1 above)
Comment (fabriciofx) [reply src/main/java/org/cactoos/text/ComparableText.java]: @ilyakharlamov You can't use a `UncheckedScalar<>(new Equals(...)).value()` (second option). You can use cast, if necessary.

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 7]
```diff
@@ -68,4 +71,64 @@ public void comparesToUncheckedText() {
...
         );
     }
+
+    @Test
+    public void equalsToItself() {
+        final Text text = new TextOf("text");
+        MatcherAssert.assertThat(
+            "Does not equal to itself",
+            text,
+            new IsEqual<>(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Use `TextIs` instead `IsEquals`

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 8]
```diff
@@ -68,4 +71,64 @@ public void comparesToUncheckedText() {
...
+
+    @Test
+    public void equalsAndHashCodeOfComparableOfTheSameText() {
+        final Text text = new TextOf("my text");
+        final Text actual = new ComparableText(text);
+        final Text expected = new ComparableText(text);
+        MatcherAssert.assertThat(
+            "Does not equal to a comparable text made from the same Text",
+            actual,
+            new IsEqual<>(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Use `TextIs` instead `IsEquals`

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 9]
```diff
@@ -68,4 +71,64 @@ public void comparesToUncheckedText() {
...
+    @Test
+    public void equalsOfDifferentText() {
+        final Text text = new ComparableText(
+            new TextOf("my value")
+        );
+        MatcherAssert.assertThat(
+            "Is equal to the completely different object",
+            text,
+            new IsNot<>(
+                new IsEqual<>(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Use `TextIs` instead `IsEquals`

File: src/test/java/org/cactoos/text/ComparableTextTest.java (hunk 3 above)
Comment (fabriciofx) [reply src/test/java/org/cactoos/text/ComparableTextTest.java]: @Iprogrammerr #1023 has solved. Please, go ahead.

File: src/test/java/org/cactoos/text/ComparableTextTest.java (hunk 7 above)
Comment (ilyakharlamov) [reply src/test/java/org/cactoos/text/ComparableTextTest.java]: @fabriciofx TestIs matcher calls ComparableText.asString(), while we are talking about the ComparableText.equals() method here, this will lead the test to check the wrong thing and produce false-positive results. I've added both IsEqual and TextIs

File: src/main/java/org/cactoos/text/ComparableText.java (hunk 1 above)
Comment (fabriciofx) [reply src/main/java/org/cactoos/text/ComparableText.java]: @ilyakharlamov Let's wait for [cactoos-matchers](https://github.com/llorllale/cactoos-matchers/issues/90).

File: src/test/java/org/cactoos/text/ComparableTextTest.java (hunk 7 above)
Comment (fabriciofx) [reply src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Right. I agree.

File: src/test/java/org/cactoos/text/ComparableTextTest.java (hunk 3 above)
Comment (ilyakharlamov) [reply src/test/java/org/cactoos/text/ComparableTextTest.java]: done

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 10]
```diff
@@ -49,23 +53,107 @@ public void comparesWithASubtext() throws Exception {
                     new SubText("from here to there", 5)
                 )
             ),
-            Matchers.is(0)
-        );
+            new IsEqual<>(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Please, put this in the same line, something like `new IsEqual<>(0)`.

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 11]
```diff
@@ -49,23 +53,107 @@ public void comparesWithASubtext() throws Exception {
...
-            new ComparableText(
+            () -> new ComparableText(
                 new UncheckedText(
                     new TextOf(txt)
                 )
             ).compareTo(
                 new ComparableText(new TextOf(txt))
             ),
-            Matchers.equalTo(0)
+            new IsEqual<>(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Same above.

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 12]
```diff
@@ -49,23 +53,107 @@ public void comparesWithASubtext() throws Exception {
...
+        ).affirm();
+    }
+
+    @Test
+    public void equalsToItself() {
+        final Text text = new TextOf("text");
+        new Assertion<>(
+            "Does not equal to itself",
+            () -> text,
+            new TextIs(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Same above.

File: src/test/java/org/cactoos/text/ComparableTextTest.java [hunk 13]
```diff
@@ -49,23 +53,107 @@ public void comparesWithASubtext() throws Exception {
...
+
+    @Test
+    public void equalsAndHashCodeOfComparableOfTheSameText() {
+        final Text text = new TextOf("my text");
+        final Text actual = new ComparableText(text);
+        final Text expected = new ComparableText(text);
+        new Assertion<>(
+            "Does not equal to a comparable text made from the same Text",
+            () -> actual,
+            new IsEqual<>(
```
Comment (fabriciofx) [inline src/test/java/org/cactoos/text/ComparableTextTest.java]: @ilyakharlamov Same above.

**Comment by llorllale** [comment]
@ilyakharlamov @fabriciofx `ComparableText` should have just extended `TextEnvelope`.

@ilyakharlamov you've technically solved #1030, so we can accept this PR right now as it is. But I'd prefer if you'd just refactor to make `ComparableText` extend `TextEnvelope`. It is a very easy refactor. Otherwise I'd require you to leave a puzzle to do it.

@ilyakharlamov I also left you comments with regards to your assertion messages

@ilyakharlamov one more thing: in PR descriptions, don't use any of GitHub's keywords like `fixes` right before the issue's ID. It'll cause the issue to automatically be closed when we merge this PR, and this is against our process. So please reword that part of the description. Thanks.

**Comment by fabriciofx** [comment]
@llorllale Ok. Thanks for your comments!

**Comment by ilyakharlamov** [comment]
@llorllale implemented in 108c9c79

**Comment by fabriciofx** [comment]
@ilyakharlamov This PR seems fine to me. @llorllale WDYT? Is it good to merge?

**Comment by llorllale** [comment]
@ilyakharlamov please remove the [github keyword](https://help.github.com/articles/closing-issues-using-keywords/) from this PR's description

**Comment by ilyakharlamov** [comment]
> @ilyakharlamov please remove the github keyword..
done

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#1031](https://github.com/yegor256/cactoos/issues/1031) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1031` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1031` doesn't exist in WBS, can't create order

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
